Imports System.Data.OleDb
Imports System.Collections
Imports System.ComponentModel

Imports Spire.Xls

Namespace CreatePivotTable
	Partial Public Class Form1
		Inherits Form
		Public Sub New()
			InitializeComponent()
		End Sub
		Private Sub btnRun_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnRun.Click
			Dim workbook As New Workbook()
			Dim sheet As Worksheet = workbook.Worksheets(0)
			' Set the value to the cells
			sheet.Range("A1").Value = "Product"
			sheet.Range("B1").Value = "Month"
			sheet.Range("C1").Value = "Count"

			sheet.Range("A2").Value = "SpireDoc"
			sheet.Range("A3").Value = "SpireDoc"
			sheet.Range("A4").Value = "SpireXls"
			sheet.Range("A5").Value = "SpireDoc"
			sheet.Range("A6").Value = "SpireXls"
			sheet.Range("A7").Value = "SpireXls"

			sheet.Range("B2").Value = "January"
			sheet.Range("B3").Value = "February"
			sheet.Range("B4").Value = "January"
			sheet.Range("B5").Value = "January"
			sheet.Range("B6").Value = "February"
			sheet.Range("B7").Value = "February"

			sheet.Range("C2").Value = "10"
			sheet.Range("C3").Value = "15"
			sheet.Range("C4").Value = "9"
			sheet.Range("C5").Value = "7"
			sheet.Range("C6").Value = "8"
			sheet.Range("C7").Value = "10"


			'Add a PivotTable to the worksheet
			Dim dataRange As CellRange = sheet.Range("A1:C7")
			Dim cache As PivotCache = workbook.PivotCaches.Add(dataRange)
			Dim pt As PivotTable = sheet.PivotTables.Add("Pivot Table", sheet.Range("E10"), cache)

			'Drag the fields to the row area.
			Dim pf As PivotField = TryCast(pt.PivotFields("Product"), PivotField)
			pf.Axis = AxisTypes.Row
			Dim pf2 As PivotField = TryCast(pt.PivotFields("Month"), PivotField)
			pf2.Axis = AxisTypes.Row
			'Drag the field to the data area.
			pt.DataFields.Add(pt.PivotFields("Count"), "SUM of Count", SubtotalTypes.Sum)
			'Set PivotTable style
			pt.BuiltInStyle = PivotBuiltInStyles.PivotStyleMedium12

			'Autofit columns generated by the pivotTable
			pt.CalculateData()
			sheet.AutoFitColumn(5)
			sheet.AutoFitColumn(6)

			Dim result As String = "CreatePivotTable_output.xlsx"
			workbook.SaveToFile(result, ExcelVersion.Version2010)
			ExcelDocViewer(result)
		End Sub

		Private Sub ExcelDocViewer(ByVal fileName As String)
			Try
				Process.Start(fileName)
			Catch
			End Try
		End Sub

		Private Sub btnClose_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnClose.Click
			Close()
		End Sub

	End Class
End Namespace
