using System;
using System.Data.OleDb;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
using System.Data;

using Spire.Xls;

namespace CreatePivotTable
{
	public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
		private void btnRun_Click(object sender, System.EventArgs e)
		{
			Workbook workbook = new Workbook();
            Worksheet sheet = workbook.Worksheets[0];
            // Set the value to the cells
            sheet.Range["A1"].Value = "Product";
            sheet.Range["B1"].Value = "Month";
            sheet.Range["C1"].Value = "Count";

            sheet.Range["A2"].Value = "SpireDoc";
            sheet.Range["A3"].Value = "SpireDoc";
            sheet.Range["A4"].Value = "SpireXls";
            sheet.Range["A5"].Value = "SpireDoc";
            sheet.Range["A6"].Value = "SpireXls";
            sheet.Range["A7"].Value = "SpireXls";

            sheet.Range["B2"].Value = "January";
            sheet.Range["B3"].Value = "February";
            sheet.Range["B4"].Value = "January";
            sheet.Range["B5"].Value = "January";
            sheet.Range["B6"].Value = "February";
            sheet.Range["B7"].Value = "February";

            sheet.Range["C2"].Value = "10";
            sheet.Range["C3"].Value = "15";
            sheet.Range["C4"].Value = "9";
            sheet.Range["C5"].Value = "7";
            sheet.Range["C6"].Value = "8";
            sheet.Range["C7"].Value = "10";


            //Add a PivotTable to the worksheet
            CellRange dataRange = sheet.Range["A1:C7"];
            PivotCache cache = workbook.PivotCaches.Add(dataRange);
            PivotTable pt = sheet.PivotTables.Add("Pivot Table", sheet.Range["E10"], cache);

            //Drag the fields to the row area.
            PivotField pf = pt.PivotFields["Product"] as PivotField;
            pf.Axis = AxisTypes.Row;
            PivotField pf2 = pt.PivotFields["Month"] as PivotField;
            pf2.Axis = AxisTypes.Row;
            //Drag the field to the data area.
            pt.DataFields.Add(pt.PivotFields["Count"], "SUM of Count", SubtotalTypes.Sum);
            //Set PivotTable style
            pt.BuiltInStyle = PivotBuiltInStyles.PivotStyleMedium12;

            //Autofit columns generated by the pivotTable
            pt.CalculateData();
            sheet.AutoFitColumn(5);
            sheet.AutoFitColumn(6);

            String result = "CreatePivotTable_output.xlsx";
            workbook.SaveToFile(result, ExcelVersion.Version2010);
            ExcelDocViewer(result);
		}

		private void ExcelDocViewer( string fileName )
		{
			try
			{
				System.Diagnostics.Process.Start(fileName);
			}
			catch{}
		}

        private void btnClose_Click(object sender, EventArgs e)
        {
            Close();
        }

	}
}
